version: '3.1'

services:
  user:
    build: ./user
    command: pnpm run start
    ports:
      - "3000:3000"
    depends_on:
      - db
  # cart:
  #   build: ./cart
  #   command: pnpm run start
  #   ports:
  #     - "3001:3001"
  catalog:
    build: ./catalog
    command: pnpm run start
    ports:
      - "3002:3002"
    depends_on:
      - db
  offer:
    build: ./offer
    command: pnpm run start
    ports:
      - "3003:3003"
    depends_on:
      - db
  booking:
    build: ./booking
    command: pnpm run start
    ports:
      - "3004:3004"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: rental
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./docker/postgres:/var/lib/postgresql/data
