version: '3.1'

services:
  user:
    build: ./user
    command: npm run start
    ports:
      - "3000:3000"
    depends_on:
      - db
  cart:
    build: ./cart
    command: pnpm run start
    ports:
      - "3001:3001"
  catalog:
    build: ./catalog
    command: pnpm run start
    ports:
      - "3002:3002"
    depends_on:
      - db
  reservation:
    build: ./reservation
    command: pnpm run start
    ports:
      - "3003:3003"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: rental
  
  
